CREATE DATABASE chirpy;
USE chirpy;

CREATE TABLE chirps(
id Int(11) AUTO_INCREMENT NOT NULL, 
author VARCHAR(225) NOT NULL, 
body VARCHAR (225) NOT NULL, 
created_at DATETIME NOT NULL,

PRIMARY KEY(id));